### PR TITLE
Fix s3 uploads and include file `path` in downloads

### LINKED ISSUE #50: XMinioInvalidObjectName: Object name contains unsupported characters.
https://sentry.data.gouv.fr/etalab/link-proxygeodatagouvfr-worker/issues/588490/

```
XMinioInvalidObjectName: Object name contains unsupported characters.
  File "/opt/link-proxy-worker/node_modules/aws-sdk/lib/services/s3.js", line 577, in Request.extractError
    resp.error = AWS.util.error(new Error(), {
  File "/opt/link-proxy-worker/node_modules/aws-sdk/lib/sequential_executor.js", line 105, in Request.callListeners
    listener.apply(self, args);
  File "/opt/link-proxy-worker/node_modules/aws-sdk/lib/sequential_executor.js", line 77, in Request.emit
    this.callListeners(listeners, eventArgs, doneCallback);
  File "/opt/link-proxy-worker/node_modules/aws-sdk/lib/request.js", line 683, in Request.emit
    origEmit.call(this, eventName, args, function (err) {
  File "/opt/link-proxy-worker/node_modules/aws-sdk/lib/request.js", line 22, in Request.transition
    self.emit(self._asm.currentState, function(err) {
...
(20 additional frame(s) were not displayed)

XMinioInvalidObjectName: Object name contains unsupported characters.
```

### PR DESCRIPTION
**Pull request by tusbar**
Fix #50

### CODE REVIEW

File: lib/utils/store.js [hunk 1]
```diff
@@ -10,6 +11,11 @@ const client = new S3({
 function upload(key, body) {
   const bucket = process.env.S3_BUCKET || 'link-proxy-files'
 
+  key = deburr(key)
+    .replace(/_/g, '-')
+    .replace(/[-]+/g, '-')
```
Comment (tusbar) [inline lib/utils/store.js]: {2,}
